<a href="https://colab.research.google.com/github/jenitta-j/jenitta-codeboosters-internship-2026/blob/main/Phase_01_Data_Engineering/Day_01_Introduction_to_Data_Engineering/Day1_DE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('student_performance.csv')

In [ ]:
df.head()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023

In [ ]:
df.tail()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
25,1026,Rekha Nair,20,Female,Electronics,2,72,77,73,63,82,Kochi,2023
26,1027,Gaurav Shukla,21,Male,Computer Science,2,84,79,75,87,87,Lucknow,2023
27,1028,Sunita Pillai,19,Female,Civil,2,60,65,68,39,73,Thiruvananthapuram,2023
28,1029,Nitin Jain,20,Male,Mechanical,2,75,76,70,50,84,Indore,2023
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023

In [ ]:
print("shape of dataset:", df.shape)
print("Number of students:", df.shape[0])
print("Number of columns:", df.shape[1])
print("Column in my dataset:")
print(df.columns.tolist())

shape of dataset: (30, 13)
Number of students: 30
Number of columns: 13
Column in my dataset:
['student_id', 'name', 'age', 'gender', 'department', 'semester', 'math_score', 'science_score', 'english_score', 'programming_score', 'attendance_percentage', 'city', 'admission_year']

In [ ]:
print("Data types :")
print(df.dtypes)

Data types :
student_id                int64
name                     object
age                       int64
gender                   object
department               object
semester                  int64
math_score                int64
science_score             int64
english_score             int64
programming_score         int64
attendance_percentage     int64
city                     object
admission_year            int64
dtype: object

In [ ]:
print("Missing values in each column:")
print(df.isnull().sum())

print("\nTotal Missing values:")
print(df.isnull().sum().sum())

Missing values in each column:
student_id               0
name                     0
age                      0
gender                   0
department               0
semester                 0
math_score               0
science_score            0
english_score            0
programming_score        0
attendance_percentage    0
city                     0
admission_year           0
dtype: int64

Total Missing values:
0

In [ ]:
print("student names:")
print(df['name'])

student names:
0       Aarav Sharma
1        Priya Patel
2        Rohit Verma
3        Sneha Reddy
4         Arjun Nair
5        Meera Joshi
6        Kiran Kumar
7        Divya Singh
8       Rahul Mishra
9         Ananya Das
10       Vikram Iyer
11       Pooja Gupta
12        Suresh Rao
13     Kavya Nambiar
14       Ajay Tiwari
15      Ritu Agarwal
16      Manoj Pandey
17    Swati Kulkarni
18    Deepak Chauhan
19      Nisha Kapoor
20     Harish Pillai
21       Tanvi Mehta
22      Sanjay Dubey
23     Preeti Saxena
24         Amit Bose
25        Rekha Nair
26     Gaurav Shukla
27     Sunita Pillai
28        Nitin Jain
29    Akanksha Yadav
Name: name, dtype: object

In [ ]:
print("Department in the dataset:")
print(df['department'].unique())

Department in the dataset:
['Computer Science' 'Electronics' 'Mechanical' 'Civil']

In [ ]:
print("How many students per Department: ")
print(df['department'].value_counts())

How many students per Department:
department
Computer Science    13
Electronics          6
Mechanical           6
Civil                5
Name: count, dtype: int64

In [ ]:
cs_students = df[df['department'] == 'Computer Science']

print(f"Number of Computer Science students: {len(cs_students)}")

print("\nDetails of Computer Science students:")

print(cs_students[['name', 'math_score', 'programming_score']])

Number of Computer Science students: 13

Details of Computer Science students:
              name  math_score  programming_score
0     Aarav Sharma          85                 91
1      Priya Patel          76                 79
4       Arjun Nair          92                 95
7      Divya Singh          88                 93
9       Ananya Das          95                 97
12      Suresh Rao          83                 88
14     Ajay Tiwari          71                 76
17  Swati Kulkarni          90                 92
19    Nisha Kapoor          79                 83
21     Tanvi Mehta          93                 96
24       Amit Bose          86                 89
26   Gaurav Shukla          84                 87
29  Akanksha Yadav          91                 94

In [ ]:
df['total_score']=df['math_score']+df['science_score']+df['programming_score']+df['english_score']

top_student=df.loc[df['total_score'].idxmax()]

print("Top student : ")
print(f"Name : {top_student['name']}")
print(f"Department : {top_student['department']}")
print(f"Total Score : {top_student['total_score']}")
print(f"Attendance : {top_student['attendance_percentage']}")

Top student :
Name : Ananya Das
Department : Computer Science
Total Score : 371
Attendance : 98

In [ ]:
df_sorted=df.sort_values(by='total_score',ascending=False)
print("top 10 student:")
print(df_sorted[['name','department','total_score','attendance_percentage']].head(10))

top 10 student:
              name        department  total_score  attendance_percentage
9       Ananya Das  Computer Science          371                     98
21     Tanvi Mehta  Computer Science          367                     97
29  Akanksha Yadav  Computer Science          365                     95
4       Arjun Nair  Computer Science          356                     90
7      Divya Singh  Computer Science          356                     96
17  Swati Kulkarni  Computer Science          354                     94
24       Amit Bose  Computer Science          336                     91
12      Suresh Rao  Computer Science          334                     88
19    Nisha Kapoor  Computer Science          327                     89
0     Aarav Sharma  Computer Science          326                     92